#!/bin/bash

read -p "Введите путь к очищаемой директории: " DELDIR

if [ -e $DELDIR ]
	then
		echo 'Указанная директория найдена'
		cd $DELDIR
		echo 'Процесс удаления'
		rm -v *.bak *.tmp *.backup
		echo 'Директория очищена'
	else
		echo 'Указанная директория не найдена! Выполнение скрипта остановлено'
		exit 2
fi
